### ISSUE TITLE
11 Timeslots out of order at 202310221000

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#18] opened 2023-11-13 14:46 UTC
Same input
I run the a2t outside of my app and the error 11 issue still happens 

![Screenshot 2023-11-14 013301](https://github.com/JamesBremner/Agents2Tasks/assets/29744306/eed6a8aa-8c04-4185-96bc-25a5c3d7dfc5)

**Comment by JamesBremner** [comment] 2023-11-13 14:50
Please post test reports to the issue that you are testing.  Do not open a new issue for every test report, only for **new** issues.

Duplicate of #15

**Closed by JamesBremner** 2023-11-13 14:50 UTC
