### ISSUE TITLE
Group name specification missing in feature definition

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#43] opened 2024-03-23 15:50 UTC
Group name doc not updated in feature definition ( It is OK in file format )

**Comment by JamesBremner** [comment] 2024-03-23 16:15
Have you tested this?

This seems to be a duplicate of #39, in particular https://github.com/JamesBremner/Agents2Tasks/commit/5891614d6a75ea9f6eb924ac09122a49cb3121fc

5 days ago you closed #39.  Did you test it before you closed it?

**Comment by JamesBremner** [comment] 2024-03-23 16:25
There was an error in the test file for #39.

Fixed now.

```
a mwalsh 1 mwalsh MAS
a example 1 example Acolyte
g A Cleaner mwalsh
g B Cleaner example mwalsh
t 202312051000 Cleaner
t 202312121000 Cleaner
t 202312191000 Cleaner
t 202312261000 Cleaner
t 202401021000 Cleaner
A 202312051000 A_group to Cleaner
A 202312051000 mwalsh in A to Cleaner
A 202312121000 B_group to Cleaner
A 202312121000 example in B to Cleaner
A 202312121000 mwalsh in B to Cleaner
A 202312191000 A_group to Cleaner
A 202312191000 mwalsh in A to Cleaner
A 202312261000 B_group to Cleaner
A 202312261000 example in B to Cleaner
A 202312261000 mwalsh in B to Cleaner
A 202401021000 A_group to Cleaner
A 202401021000 mwalsh in A to Cleaner
```

**Comment by JamesBremner** [comment] 2024-03-25 13:50
Hello?

**Comment by rejkid** [comment] 2024-03-26 13:45
Yep. Everything seems to be OK. I have some issues with my application. Would you mind updating documentation?

**Comment by rejkid** [comment] 2024-03-26 15:16
User supplied group name #40 - the new format for group names

**Comment by JamesBremner** [comment] 2024-03-26 15:30
Fixed

**Closed** 2024-03-28 12:37 UTC
Labels: documentation, state:test
